services:
  pgdatabase:
    image: postgres:15
    container_name: pgserver ### Connections --> Host name/adress
    environment: 
      - POSTGRES_USER="root"
      - POSTGRES_PASSWORD="root"
      - POSTGRES_DB="health"
    volumes:
      - ./health_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" ### Connections --> Port: 5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"

